name: Arma Checks And Build

on: [push, pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the source code
      uses: actions/checkout@master
    - name: Validate Config
      run: python3 tools/SQF-validate/config_style_checker.py
    - name: Check for BOM
      uses: arma-actions/bom-check@master
      with:
        path: 'Vindicta.Altis'

  validate-with-sqf-vm:
    runs-on: windows-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@master
    - name: Validate SQF with SQF-VM
      run: |
        cd Vindicta.Altis
        ..\tools\SQF-VM\sqfvm.exe -a --no-execute-print --disable-macro-warnings --load . -i D:\a\Vindicta\Vindicta\Vindicta.Altis\Tests\RunTests.sqf

  build:
    runs-on: windows-latest
    needs: [validate, validate-with-sqf-vm]
    steps:
    - name: Checkout the source code
      uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Build
      run: |
        $env:RUST_BACKTRACE= 1
        cd Vindicta-Addon
        ..\tools\setup_and_build.bat
        .\tools\hemtt.exe build --release --force --nowarn
        $verDir = (Get-ChildItem -Path ..\_build -Filter "vindicta_v*").Name
        .\tools\armake_w64 build -f  "..\_build\$($verDir)" ".\releases\1.0.0.0\@vindicta\addons\$($verDir).pbo" -w unquoted-string -w redefinition-wo-undef
        .\tools\armake_w64 sign -f .\releases\keys\vindicta.biprivatekey ".\releases\1.0.0.0\@vindicta\addons\$($verDir).pbo"
        
    - uses: actions/upload-artifact@v1
      with:
        name: build
        path: Vindicta-Addon/releases/1.0.0.0
  
  upload:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Download build
      uses: actions/download-artifact@v1
      with:
        name: build
    - name: Push to Steam Workshop
      uses: arma-actions/workshop-upload@v1
      with:
        appId: '107410'      # default
        itemId: '1729562743' # Vindicta-Dev
        contentPath: '@vindicta'
        changelog: 'No changelog yet'
      env:
        STEAM_USERNAME: ${{ secrets.SECRET_0 }}
        STEAM_PASSWORD: ${{ secrets.SECRET_1 }}
