name: Validate Test and Build
on: [push, pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the source code
      uses: actions/checkout@master
    - name: Validate Config
      run: python3 tools/SQF-validate/config_style_checker.py
    - name: Check for BOM
      uses: arma-actions/bom-check@master
      with:
        path: 'Vindicta.Altis'

  test:
    runs-on: windows-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@master
    - name: Validate SQF with SQF-VM
      run: |
        cd Vindicta.Altis
        ..\tools\SQF-VM\sqfvm.exe -a --no-execute-print --disable-macro-warnings --load . -i D:\a\Vindicta\Vindicta\Vindicta.Altis\Tests\RunTests.sqf

  build:
    runs-on: windows-latest
    needs: [validate, test]
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Build
      run: |
        $env:RUST_BACKTRACE=1
        cd Vindicta-Addon
        .\tools\buildv2.ps1
        
    - uses: actions/upload-artifact@v1
      with:
        name: build
        path: Vindicta-Addon/release

    - uses: actions/upload-artifact@v1
      with:
        name: dev
        path: Vindicta-Addon/dev
    
