name: Publish to Workshop [OLD PAGE]

on:
  push:
    branches:
      - master-old-workshop

jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@master

    - name: Validate Config
      run: python3 tools/SQF-validate/config_style_checker.py

    - name: Check for BOM
      uses: arma-actions/bom-check@master
      with:
        path: 'Vindicta.Altis'

  test:
    runs-on: windows-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@master

    - name: Validate SQF with SQF-VM
      run: |
        cd Vindicta.Altis
        New-Item .\config\user_local_config.hpp -ItemType File
        ..\tools\SQF-VM\sqfvm.exe -a --no-execute-print --disable-macro-warnings --load . -i D:\a\Vindicta\Vindicta\Vindicta.Altis\Tests\RunTests.sqf

  build:
    runs-on: windows-latest
    timeout-minutes: 5
    needs: [validate, test]
    steps:
    - uses: actions/checkout@master

    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Set version
      run: |
        $major = "0"
        $minor = "45"
        Set-Content -Path .\configs\majorVersion.hpp -Value $major -Force -NoNewline
        Set-Content -Path .\configs\minorVersion.hpp -Value $minor -Force -NoNewline

    - name: Build
      run: |
        cd Vindicta-Addon
        .\tools\buildv2.ps1 -patch 20
        
    - uses: actions/upload-artifact@v1
      with:
        name: build
        path: Vindicta-Addon/release
          
    - uses: actions/upload-artifact@v1
      with:
        name: _uploadurl
        path: _uploadurl

  upload:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [build]
    steps:
    - name: Download build
      uses: actions/download-artifact@v1
      with:
        name: build

    - uses: actions/download-artifact@v1
      with:
        name: _uploadurl
        path: .

    - name: Publish to Steam Workshop
      uses: arma-actions/workshop-upload@v1
      with:
        appId: '107410'      # default
        itemId: '1729562743' # Vindicta Dev at Sparker's account https://steamcommunity.com/sharedfiles/filedetails/?id=1729562743
        contentPath: 'build/@vindicta'
        changelog: "Add notification at start up"
      env:
        STEAM_USERNAME: ${{ secrets.SECRET_0 }}
        STEAM_PASSWORD: ${{ secrets.SECRET_1 }}
