name: Release Drafter

on:
  push:
    branches:
      - master

jobs:
  update-release-draft:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      
    - name: Draft Release
      id: draft_release
      uses: release-drafter/release-drafter@v5.6.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
