name: Test New Builder

on:
  push:
    branches:
      - build-tools

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 5

    steps:
    - name: Checkout the code
      uses: actions/checkout@master
      
    - name: List files
      run: |
        write-host "Hello from step list files"
        Get-Location | write-host
        Get-ChildItem | write-host
    - name: Build Missions
      run: '.\tools\Builder\buildMissions.ps1 -verPatch ${{ github.run_number }}'
